### ISSUE TITLE
Baseline scores with D2KB experiment

### ISSUE THREAD

**Issue by alexanderpanchenko** [dice-group/gerbil#247]
Hello, 

I am struggling to understand the precision and recall metrics for the unknown URIs (the EE category in the report such as the one below). 

<img width="1229" alt="screen shot 2018-03-18 at 5 21 33 pm" src="https://user-images.githubusercontent.com/1456830/37568115-f285df40-2ad0-11e8-8b12-17725d8ea2fc.png">

In your wiki, it is indicated that "The EE scores are the opposite of the InKB scores. They consider only those entities that have no URI of the KB.". However, I do not understand, how you can say if the URI is correct if it is out of the KB. 

Besides, the image above presents results of the evaluation on the D2KB experiment with the 'Derzcynski' dataset. The NIF web service which is evaluated always returns the URI "http://dbpedia.org/resource/nonsense". I am really struggling to understand how such a baseline can yield non-zero F-score. 

Thanks in advance for your explanations,

Best,
Alex.

**Comment by MichaelRoeder** [comment]
Regarding the question how we identify URIs as correct that are outside of the KB, please have a look at https://github.com/dice-group/gerbil/wiki/URI-matching (especially at the example).

However, assigning entities with `http://dbpedia.org/resource/nonsense` should lead to an F1-measure of 0.0 because `dbpedia.org` is a known KB.

@TortugaAttack could you please have a look at this and check whether we can reproduce this behaviour, locally?

**Comment by alexanderpanchenko** [comment]
Hello,

Thank you for the quick reply. 

Regarding the URIs that are outside of the KB: Can you please clairify row 7 of the table at https://github.com/dice-group/gerbil/wiki/URI-matching? 

According to this document, two non-KB URIs are considered TP, like below:

```
7 | http://aksw.org/notInWiki/Berlin | http://example.org/unknown/Berlin_X | tp

```

Does this mean that that this URI will also be considered as TP (if yes, then it is not clear to me what is the intuition why it should be so as the unknown URI can point to any resource):

```
7 | http://aksw.org/notInWiki/Berlin | http://unknown.org/blah/nonsense | tp
```

**Comment by MichaelRoeder** [comment]
Yes, it is counted as true. Yes, it _could_ point to any resource. However, the system has found that a) it is an entity and b) it is not in the KB. From that point on, it is simply not possible to figure out whether the URI is pointing to the correct resource, simply because there is no URI of a "well-known" KB that is pointing to this resource. That is the reason why we count them as `tp`. I understand that it might sound strange at the beginning, but going much deeper in the evaluation is not possible.

In general, it would be possible to add further checks. We could check for co-reference resolution inside of documents (i.e., if the same emerging entity occurs twice inside a document, it should have the same URI while different entities should have different URIs). That would already be possible with the task definition. We haven't implemented this until now because the cases in which the emerging entities occur multiple times in a single document (with different labels) are rare. However, extending this further to inter-document co-reference resolution (i.e., the same emerging entity in different documents should have the same URI) would create a completely new layer to the task. So for something like that, we would have to define a new experiment type :thinking: 

Does this answer your question?

**Comment by alexanderpanchenko** [comment]
Thanks for these detailed explanations: this is a design choice and it makes no problem for my experiment per se, but I just was not sure if I am understanding these design choices correctly. Maybe even some passages from your answer can be poster in the abovementioned wiki page (as during reading it for the first time i was not able to grasp the intuitions behind this design choice).

PS: Just a small suggestion: maybe some URI resolving can be done for such unknown entities (agains a real DNS) and if the IP is the same or linking to a known entity this can be used as an additional information. But of course this is pretty heavy-weight method.
