### ISSUE TITLE
Rename AGDISTIS to AGDISTIS/MAG

### ISSUE THREAD

**Issue by RicardoUsbeck** [dice-group/gerbil#257]
Since the new implementation of the webservice of agdistis running via akswnc9, we would like to rename the webservice to be also compliant with the new publication.

**Comment by DiegoMoussallem** [comment]
Not rephrased.

**Comment by MichaelRoeder** [comment]
I think you are mixing up two things here. It has been changed:
https://github.com/dice-group/gerbil/blob/master/src/main/properties/annotators.properties#L6

However, the online instance we have is not running the latest version since there was no new release. I have updated it now. Please check again.

**Comment by DiegoMoussallem** [comment]
Got it, thanks for updating the online version :)
