### ISSUE TITLE
Check if micro F1 measure for QA uses-case is working correctly

### ISSUE THREAD

**Issue by D063520** [dice-group/gerbil#285]
Hi,

I noticed that when running an experiment like this:

 http://gerbil-qa.aksw.org/gerbil/experiment?id=201809180000

I nearly always get a micro F-measure near to 0. Could you give a look if this is the expected behaviour and if yes, where this number comes from.

Cordially
D063520

**Comment by Suganya31** [comment]
Hi Dennis,

The F-measure is reduced because of some questions which has a large set of Golden Answers while the system returns very few. I calculated the results for two types of datasets; one with three questions and the other including  an additional question for which the Golden Answer has 117 results and the system returns only one result.  For both the cases, Gerbil gives the correct response. Please find my calculations below.

**F-Measure Calculation:**

1. What is the time zone of Salt Lake City?

**GOLDEN ANSWER:1**

http://dbpedia.org/resource/Mountain_Time_Zone

**SYSTEM ANSWER:** 

http://dbpedia.org/resource/Mountain_Time_Zone

**Recall_1**=1/1=1
**Precision_1**=1/1=1
**F-measure_1**=2/2=1

2. "What were the names of the three ships by Columbus?

**GOLDEN ANSWER:3**

http://dbpedia.org/resource/Santa_María_(ship)
http://dbpedia.org/resource/Pinta_(ship)
http://dbpedia.org/resource/Niña

**SYSTEM ANSWER:** 
http://dbpedia.org/resource/Bruce_Peddie

**Recall_2**=0
**Precision_2**=0
**F-measure_2**=0

3."What were the original 13 British colonies?"

**GOLDEN ANSWER:12**

http://dbpedia.org/resource/Province_of_South_Carolina
http://dbpedia.org/resource/Chesapeake_Colonies"
http://dbpedia.org/resource/Chesapeake_Colonieshttp://dbpedia.org/resource/New_England_Colonies"
http://dbpedia.org/resource/Province_of_Georgia"
http://dbpedia.org/resource/Colony_of_Virginia"
"http://dbpedia.org/resource/Middle_Colonies"
http://dbpedia.org/resource/Province_of_New_Hampshire"
"http://dbpedia.org/resource/Province_of_Pennsylvania"
 "http://dbpedia.org/resource/Southern_Colonies"
"http://dbpedia.org/resource/Province_of_Massachusetts_Bay"
"http://dbpedia.org/resource/Connecticut_Colony"
"http://dbpedia.org/resource/Delaware_Colony"
"http://dbpedia.org/resource/Province_of_New_Jersey"

**SYSTEM ANSWER:** 
http://dbpedia.org/resource/British_Bull_Dog_revolver
http://dbpedia.org/resource/Enfield_revolver
http://dbpedia.org/resource/Webley_Revolver

**Recall_3**=0
**Precision_3**=0
**F-measure_3**=0

**Calculating Micro and Macro Values:**


**Macroprecision**=1+0+0/3=**0.3333333333333333**
**Macrorecall**=1+0+0/3=**0.3333333333333333**
**Macrofmeasure**=1+0+0/3=**0.3333333333333333**
**Microprecison**=(TP1+TP2+TP3)/(TP1+TP2+TP3+FP1+FP2+FP3)=(1+0+0)/(1+0+0+0+1+3)=**0.2**
**Microrecall**=(TP1+TP2+TP3)/(TP1+TP2+TP3+FN1+FN2+FN3(1+0+0)/(1+0+0+0+3+13)=**0.05882352941**
**Microfmeasure**=2(0.2)(0.05882352941)/(0.2+0.05882352941)=**0.0909090909069834** 

**Adding the question which has 117 golden answers but the system returns only one relevant answer**

4. Give me all chemical elements

**GOLDEN ANSWER**:117

**System Answer:**
value: "http://dbpedia.org/resource/Chemical_element\" 

**Recall_4**=1/117=0.008547008547008548
**Precision_4**=1/1
**F-measure_4**=0.016949152542372885

**Recalculating Micro and Macro Values:**

**Macroprecision**=1+0+0+1/4=**0.5**
**Macrorecall**=1+0+0+008547008547008548/4=**0.25213675213675213**
**Macrofmeasure**=1+0+0+0.016949152542372885/4=**0.2542372881355932**

**Microprecison**=(TP1+TP2+TP3+TP4)/(TP1+TP2+TP3+TP4+FP1+FP2+FP3+FP4)=(1+0+0+1)/(1+0+0+0+1+1+3+0)=**0.3333333333333333**
**Microrecall**=  (TP1+TP2+TP3+TP4)/(TP1+TP2+TP3+TP4+FN1+FN2+FN3+FN4) =(1+0+0+1)/(1+0+0+1+0+3+13+116)=**0.014925373134328358**
**MicroFmeasure**=2(0.3333333333333333)(0.014925373134328358)/(0.3333333333333333+0.0149253731343283589)=**0.028571428571428574**

I have attached the evaluation results of GERBIL for both the cases. I will add the unit test case for the F-measure calculation as well. I hope this helps.

Thanks and Regards,
Suganya

![resultswith3questions](https://user-images.githubusercontent.com/32637704/52583827-d813e080-2e30-11e9-9b0c-b3835e25ad96.png)
![resultswith4questions](https://user-images.githubusercontent.com/32637704/52583829-d813e080-2e30-11e9-8182-931a8bf98c74.png)

**Comment by RicardoUsbeck** [comment]
I take this silence as a "works".
