### ISSUE TITLE
Why is there no wiki uri prefix in org.aksw.gerbil.evaluate.DefaultWellKnownKB property？

### ISSUE THREAD

**Issue by renli1024** [dice-group/gerbil#325]
Hello, at first much thanks for providing such a great project! 

I’m trying to run the program locally and add my own annotator in it by implementing the adapter. Now I am in the attempt state where I plan to receive the dataset input and output the dataset annotations in my annotator class, aims to run through the workflow of the project successfully first, and each evaluation result should be 1.0. The task I run is D2KB, the dataset I used is ACE2004. 

However, when I was testing the program I found that results are not all 1.0 because of 4 fp and fn instances. I dug a little deeper and found it is because annotator marking is regarded as IN_KB but the corresponding gold standard is regarded as EE. Here is an example from document ACE2004 dataset:
<img width="904" alt="Screen Shot 2019-07-08 at 19 29 25" src="https://user-images.githubusercontent.com/47926776/60808046-f8668200-a1b9-11e9-92b4-17144dc63eec.png">

<img width="909" alt="Screen Shot 2019-07-08 at 19 29 52" src="https://user-images.githubusercontent.com/47926776/60808067-03211700-a1ba-11e9-9151-3beda77b9d5c.png">

We can see that the URI of annotator and gold standard is the same and URI set also has wiki URI, but this instance is assigned to both fp and fn. Because the classBits field of annotatorResults is {0} (denotes IN_KB) and goldStandard is {1} (denotes EE). Furthermore, I found whether the URI is in KB is actually determined by org.aksw.gerbil.evaluate.DefaultWellKnownKB property, [here](https://github.com/dice-group/gerbil/blob/master/src/main/properties/gerbil.properties#L58-L63), which has no wiki URI prefix. Thus, if there is only wiki URI the system will not think it is in KB. I wonder if it is a bug or designed by some other reason?

Moreover, I added a line of code:  _org.aksw.gerbil.evaluate.DefaultWellKnownKB=http://en.wikipedia.org/wiki_ in the gerbil.properties file, after which the problem is solved and evaluation results all become 1.0.

Hope I have expressed my problem clearly. Thanks a lot for your time in advance!

**Comment by MichaelRoeder** [comment]
Thanks for this insight. It could be a bug. However, to be able to recreate the issue, it would be crucial that you provide all 4 FP/FN examples as text (i.e., for each annotation we would need the URI expected by the gold standard and the URI that is returned by your annotator). Please make sure to provide them as text since we can not copy the URIs from a screentshot :wink: 

Typically, having Wikipedia as "well known KB" is not necessary, since all entities of Wikipedia are directly translated to DBpedia URIs using the sameAs retrieval mechanism. However, this seems to lead to issues in your example, because both - the URI in the gold standard as well as the URI returned by your system seem to be wrong (it should be `http://en.wikipedia.org/wiki/USS_Cole_(DDG-67)` instead of `http://en.wikipedia.org/wiki/USS_COLE_(DDG-67)`).

**Comment by renli1024** [comment]
Much thanks for your quick reply Michael, 

I have uploaded the text file of the fn&fp examples and you can examine it. For my annotator, it actually does not deal with the dataset but only parses it and returns the golden annotations. Thus, the evaluation result of the system should all be 1.0. 

My two cents worth of opinion, the problem may come from two aspects. First is the retrieval process, cause there is only wiki URI in the golden URI set, indicating wiki URI is not translated to DBpedia correctly. For the reason of network, I cannot directly download the _entitycheck_ and _sameAs_ cache file inside the system, so I get the files [here](https://github.com/dice-group/gerbil/issues/163), which are provided in 2016 and maybe sort of out date. Second, the problem may also be caused by ACE2004 dataset. For the "USS_COLE_(DOG-67)" instance, it is annotated by the dataset as golden standard but cannot point to the correct wiki page. The same condition also exits in other fn&fp examples provided in my text.

Thanks for your time!

**Comment by MichaelRoeder** [comment]
The issue is very simple: GERBIL expects that the gold standard is correct, but might contain outdated URIs. It will translate the Wikipedia-based URIs of the dataset to DBpedia URIs. After that, it turns out, that the DBpedia entities are not existing so it will change them to these `unknown_entity` URIs.

Now, when your "system" is answering with the same data, GERBIL does not check the URIs of the system whether they are outdated or not. GERBIL has been created for web services and we simply assume that the system is up to date :wink: 
It will translate the Wikipedia URIs to DBpedia URIs.

The evaluation process of GERBIL will see unknown URIs on the one side and some DBpedia URIs on the other side which will automatically lead to a missmatch (although the additional Wikipedia URIs are the same).

So, the issue is not that the transformation of the URIs is not working or something similar. The problem is that the "system" that you have uses outdated / non existing URIs which is not expected by GERBIL. 

Coming back to your original question: if the Wikipedia URIs would be marked as "well-known" URIs, we would have to run checks for the Wikipedia URIs as well, the Wikipedia would state that they are not valid and you would see the same effect.
(although that it is possible that we would have to change the check for this kind of URIs :thinking: )

However, from a practical point of view, you could avoid this by turning the entitiy check off. This is described at https://github.com/dice-group/gerbil/issues/130#issuecomment-227480919

**Comment by renli1024** [comment]
Thanks a lot for your detailed explaining and my question is cleared.

Thank you!
