### ISSUE TITLE
Datasets missing when launching from remote server

### ISSUE THREAD

**Issue by Wenyueh** [dice-group/gerbil#392]
Hello, 

Thank you for this convenient tool!

I have some issue finding datasets when launching GERBIL from the remote server. When opening GERBIL platform locally, I can see the below datasets: 
<img width="311" alt="Screen Shot 2021-06-15 at 12 20 28 AM" src="https://user-images.githubusercontent.com/28013619/121992713-27a3a780-cd70-11eb-89db-d476324c0910.png">
<img width="310" alt="Screen Shot 2021-06-15 at 12 20 34 AM" src="https://user-images.githubusercontent.com/28013619/121993001-b6182900-cd70-11eb-830a-b8ba1aaa295b.png">

However, when connecting from a remote server, a lot of datasets seem to be missing such as AIDA and AQUIANT:
<img width="314" alt="Screen Shot 2021-06-15 at 12 14 07 AM" src="https://user-images.githubusercontent.com/28013619/121992771-4a35c080-cd70-11eb-97ed-1db8377e8cee.png">
What could be the problem? Could you give me some idea? Thank you very much!

**Comment by MichaelRoeder** [comment]
Thank you for your interest in GERBIL.

We are not allowed to put all datasets in our `gerbil_data.zip` file because of licensing reasons. In our [wiki](https://github.com/dice-group/gerbil/wiki/Licences-for-datasets), you can find a list of datasets with more details about there license, where you may get the dataset and how you can integrate it with your local GERBIL server.

**Comment by Wenyueh** [comment]
Thank you very much!

**Comment by Wenyueh** [comment]
Thank you very much!

It's probably a silly question but I wonder how I am going to use AIDA dataset after obtaining AIDA-YAGO2-dataset.tsv? I put the tsv file in the directory gerbil_data/datasets/aida/AIDA-YAGO2-dataset.tsv but still cannot see the AIDA option on the web interface. When I tried to upload the AIDA-YAGO2-dataset.tsv dataset directly, an error occurs as below:
<img width="1165" alt="Screen Shot 2021-06-17 at 12 54 12 AM" src="https://user-images.githubusercontent.com/28013619/122333710-8ac74280-cf06-11eb-8591-d5a8fe7d74fe.png">

**Comment by MichaelRoeder** [comment]
The path looks fine. In GERBIL, the path is defined in the [`datasets.properties`](https://github.com/dice-group/gerbil/blob/master/src/main/properties/datasets.properties#L15) file.

While the start of the server, GERBIL prints log messages regarding the single datasets like the following lines:
```
2021-06-17 10:27:05,356 [localhost-startStop-1] INFO [org.aksw.gerbil.web.config.DatasetsConfig] - <Found dataset configuration ("AIDA/CoNLL-Training",cached=true,expType={A2KB},constr.=public org.aksw.gerbil.dataset.impl.aida.AIDACoNLLDataset(java.lang.String,java.lang.String,java.lang.String),args=[gerbil_data/datasets/aida/AIDA-YAGO2-dataset-update.tsv, 1, 946])>
2021-06-17 10:27:05,357 [localhost-startStop-1] INFO [org.aksw.gerbil.web.config.DatasetsConfig] - <Check for dataset "Bengal EN 13 (star 10 long)" failed. It won't be available.>
```
The first line reports that a dataset definition has been found. The second line reports that a dataset won't be available because a check failed (e.g., some file of the dataset is not available). Can you please check what GERBIL reports for the 4 AIDA datasets when you start it?

**Comment by Wenyueh** [comment]
Thank you for the quick reply!

The AIDA dataset worked properly after two days I uploaded it to the directory. GERBIL did print out the same log message as the lines above. 

Thank you again.
