### ISSUE TITLE
deny the annotator

### ISSUE THREAD

**Issue by Lisilin87** [dice-group/gerbil#431]
GERBIL deny my annotator without any error output, so I don't know how to debug,
The web page:
![image](https://github.com/dice-group/gerbil/assets/94789065/95f2b106-6705-47da-85b1-403d9f54cad7)
The 1234 port shows:
![image](https://github.com/dice-group/gerbil/assets/94789065/f87d50d8-5472-4618-bf33-e670ded732d0)
The 1235 port shows:
![image](https://github.com/dice-group/gerbil/assets/94789065/bafc2981-400f-4b48-a061-ebbda4ce5488)

My annotator is follow the Entqa, and the annotater return '[]' a empty list will get the same web page. 
How to solve these.

**Comment by MichaelRoeder** [comment]
Thank you for using GERBIL to benchmark your approach.

I am not sure whether I understand your problem correctly. How do you know that GERBIL does not accept your annotator? From your screenshots, everything looks fine.

**Comment by Lisilin87** [comment]
Sorry，when i saw the '×', i subconsciously thought GERBIL refuse my annotator. Now, i can run experiment successfully. But i still encounter some problems。I run my entity linking system only on AIDA-CONLL test-B，but my
annotater still receive nothing after 1 hour, and the 1234 port give me some warn:
![image](https://github.com/dice-group/gerbil/assets/94789065/e378a686-6f3e-45bd-840f-dc93a7686b85)
Is this normal ? 
Is this error the same as [https://github.com/dice-group/gerbil/issues/137](url)

**Comment by MichaelRoeder** [comment]
I think you are facing two issues at once.

### 1. CoNLL File Format

The CoNLL files are typically tab-seperated files. I assume that your file has been edited by a program, which was configured wrongly and thought that it has to add quotation marks `"` around IRIs, which contain a comma, e.g., `http://en.wikipedia.org/wiki/Washington,_D.C.` would be transformed to `"http://en.wikipedia.org/wiki/Washington,_D.C."`. GERBIL reads these values but does not expect the quotation marks and, hence, is not able to understand this information.

However, since I don't know your file, I would suggest to open the file and check whether there are quotation marks around some of the IRIs.

### 2. Entity Checking and SameAs Retrieval

I can imagine that you face the same situation as in #137. Depending on the system that you would like to benchmark, I see several ways to go. You can disable the complete functionality or single parts of it. That will make your experiments faster but you will have to be careful with your results since they rely on an old, partly outdated dataset. Depending on the version of the knowledge base your system relies on, the results might be partly wrong.

You can also disable single parts of it, e.g., you could create a local DBpedia index and disable calls to the online DBpedia. Or you invest the time and let it run. It will take quite some time but if you activate all the caches, it should do the job only once.

**Comment by MichaelRoeder** [comment]
I think you are facing two issues at once.

### 1. CoNLL File Format

The CoNLL files are typically tab-seperated files. I assume that your file has been edited by a program, which was configured wrongly and thought that it has to add quotation marks `"` around IRIs, which contain a comma, e.g., `http://en.wikipedia.org/wiki/Washington,_D.C.` would be transformed to `"http://en.wikipedia.org/wiki/Washington,_D.C."`. GERBIL reads these values but does not expect the quotation marks and, hence, is not able to understand this information.

However, since I don't know your file, I would suggest to open the file and check whether there are quotation marks around some of the IRIs.

### 2. Entity Checking and SameAs Retrieval

I can imagine that you face the same situation as in #137. Depending on the system that you would like to benchmark, I see several ways to go. You can disable the complete functionality or single parts of it. That will make your experiments faster but you will have to be careful with your results since they rely on an old, partly outdated dataset. Depending on the version of the knowledge base your system relies on, the results might be partly wrong.

You can also disable single parts of it, e.g., you could create a local DBpedia index and disable calls to the online DBpedia. Or you invest the time and let it run. It will take quite some time but if you activate all the caches, it should do the job only once.

**Comment by MichaelRoeder** [comment]
Closed after a year of inactivity.
